/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nV_Parser */

#ifndef _Included_nV_Parser
#define _Included_nV_Parser
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     nV_Parser
     * Method:    _constructor
     * Signature: (J)J
     */
    JNIEXPORT jlong JNICALL Java_nV_Parser__1constructor
    (JNIEnv *, jclass, jlong);

    /*
     * Class:     nV_Parser
     * Method:    _destructor
     * Signature: (J)V
     */
    JNIEXPORT void JNICALL Java_nV_Parser__1destructor
    (JNIEnv *, jclass, jlong);

    /*
     * Class:     nV_Parser
     * Method:    _parse
     * Signature: (JLjava/lang/String;)J
     */
    JNIEXPORT jlong JNICALL Java_nV_Parser__1parse
    (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
